sudo: required

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t cd2team/docker-jenkins:lts ./

deploy:
  provider: script
  script:
    - docker push cd2team/docker-jenkins:lts
